### PR TITLE
Tmp vng new

### PR DESCRIPTION
**Pull request by ciciplusplus**

### CODE REVIEW

**Comment by ciciplusplus** [comment]
> omg in your build bia gets to the sound selection but crashes when selecting

what is bia?

**Comment by makaher** [comment]
> > omg in your build bia gets to the sound selection but crashes when selecting
> 
> what is bia?



> > omg in your build bia gets to the sound selection but crashes when selecting
> 
> what is bia?

Brothers in arms

**Comment by ciciplusplus** [comment]
> > > omg in your build bia gets to the sound selection but crashes when selecting
> > 
> > what is bia?
> 
> Brothers in arms

I'm sorry for them

**Comment by makaher** [comment]
> > > > омг в вашей сборке bia добирается до выбора звука, но вылетает при выборе
> > > 
> > > 
> > > что такое bia?
> > 
> > 
> > Братья по оружию
> 
> Я сожалею о них



> > > > omg in your build bia gets to the sound selection but crashes when selecting
> > > 
> > > 
> > > what is bia?
> > 
> > 
> > Brothers in arms
> 
> I'm sorry for them

What?

**Pull request closed without merging**
